### ISSUE TITLE
Private Chat room 백엔드 프론트엔드 통신 로직 관련 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#115]
## Private Chat room 정의
- 비공개방은 DM과 단체방이 있음
- 참여 가능한 채팅 리스트에는 노출되지 않음
- 단체방은 Chat 방만들기->비공개방 선택으로 만들면 방이 생성되고 참여중인 유저리스트->+유저를 클릭해 초대하는 형식
- DM방은 유저프로필에서 DM하기를 통한 접근 -> 비공개방 2인 방으로 생성->+유저 버튼은 없음
## 문제
- 비공개방으로 초대 당하는 유저 A는 방에 들어가 있지 않은 상황, 서버 클라이언트간 이벤트도 없음
- 수락에 대한 부분도 없음 

### 제안
- DM 혹은 단체방으로 초대하는 순간 초대 받은 유저 A에게 Invited(예시) 이벤트를 서버가 보냄
- 클라이언트는 이벤트를 받고 참여중인 채팅방에 리스트를 추가한 후 거절, 수락 선택 메시지를 보여줌
- 클라이언트가 거절하는 경우 참여중인 채팅방에 리스트에서 삭제, 서버한테 거절 메시지를 보냄(SEND)->초대한유저(B) 및 해당 방 참여자들은 거절메시지를 받음
- 클라이언트가 수락하는 경우 Join 이벤트를 서버에 보냄, 그 이후로 일반적인 메시지 통신 
- 수락 거절 선택 전에는 해당 채팅방의 메시지 받지(저장하지) 않음 

---
의견 바랍니당

**Comment by scarf005** [comment]
- `INVITE` 이벤트를 만들어 초대받을때마다 실행되게 하는 것이 어떨까요?

**Comment by peas856** [comment]
초대받을때마다 '실행' 이 무슨뜻인가요?

**Comment by scarf005** [comment]
`socket.on('INVITE', () => /* */)`

**Comment by peas856** [comment]
아아 맞아요 방 번호랑 메시지를 받아서 updateJoinedRoom 실행해서 방 추가하고 뭔가 초대수락하는 메시지를 보여줘야할거같아요

**Comment by hoikii** [comment]
프론트에서는 소켓을 언제 만들어주고 있나요?
채팅탭에 한번도 들어가지 않은 사용자도 INVITE 이벤트를 받을 수 있나요?

**Comment by peas856** [comment]
로그인 완료 후 소켓을 만들어줄 계획입니다
- 따라서 Invite 이벤트는 받는건 문제 없는데 socket.on('INVITE', func) 에서 func에서 처리해야할 것들이 chat 컴포넌트에 있어서 그것이 문제입니다..

**Comment by scarf005** [comment]
정 안 된다면 아예 소켓을 인자로 컴포넌트에 보내는 것도 방법이기는 합니다...

**Comment by peas856** [comment]
그렇게 하려고 했는데 그러면 socket.on 이벤트 등록이 하위컴포넌트를 실행할때 등록되거나(useeffect) 하위컴포넌트 랜더링할때마다 이벤트 등록이 되는 문제가 잇는것 같더라구요. 테스트를 다시 해봐햐하긴하지만

**Comment by peas856** [comment]
생각해봤는데 게임초대만 수락, 거절 과정을 추가하고 채팅의 경우 슬랙채팅처럼 INVITE 이벤트를 받으면 JOIN 이벤트를 서버에 보내서 그 이후로 메시지를 받는게 낫겠네요.

**Comment by peas856** [comment]
@hoikii 님 프론트에서 채팅방 초대를 누르면(a가 b를 초대하면)
socket.emit('INVITE', {invitedUserUid:number, roomId:number, roomType: string}
을 보내고 서버에서는 b를 방에 포함시키고 b에게 소켓으로 방에 조인되었다는 NOTICE 이벤트를 보내면 되지 않을까요?
@scarf005 그럼 NOTICE 이벤트를 받고 참여중인 방 목록을 업데이트 해서 유저 b가 초대된 방을 클릭할 수 있도록 하면 되지 않을까요

두분 의견 바랍니당

**Comment by peas856** [comment]
[프론트]
Roomtype은 1. Public 2. Private 3.DM으로 하고 

1 -> 채팅화면, Input, 참여중인 유저 리스트 + 방비번 추가 및 변경 컴포넌트
2 -> 채팅화면, Input, 참여중인 유저 리스트 + 유저 초대 기능(Input + submit 버튼)
3 -> 채팅화면, Input, 참여중인 유저 리스트

이렇게 컴포넌트를 보여주면 되지 않을까요?

**Comment by hoikii** [comment]
비번있는 방이라도 초대를 통해 들어갈 땐 비번을 받을 필요 없겠죠?
백에서는 b를 조인시키기 전에 a가 roomId의 참여자인지 정도만 확인하면 될 것 같은데, 악용의 여지가 있을런지 모르겠습니다.

제가 이해하기론 `<공개방 | 공개방with비번 | 비공개방>` 이 과제 요구사항인 것 같은데,
우리가 DM을 _2명만 참여 가능한 비공개방_으로 구현하기로 했으니까
`Public | Protected | Private | DM` 으로 구분하는 건 어떨까 싶어요.

**Comment by peas856** [comment]
Public | Protected | Private | DM 
이렇게 구분하는게 나을것 같아요
초대기능은 일단 비공개방에만 넣으려고 생각중입니다.

**Comment by peas856** [comment]
Friend tab에서 DM보내기 제거, DM 보내는 사람->chatPanel 컴포넌트, 받은 사람 참가중인 채팅리스트에 추가
