### ISSUE TITLE
프론트엔드에서 아바타를 못 읽어옴

### ISSUE THREAD

**Issue by 42-saoh** [exciting-transcendence/transcendence#124]
프론트 처음 닉네임 등록 창에서 default.jpg 이미지를 못 불러오고 마찬가지로 friend 창에서도 못 불러옴, 이미지를 수정해도 못 불러옴
401 unauth 가 나온다. 프론트에서 토큰을 보관하지 않고 있기 때문이라 생각되고 확인 부탁합니다.

**Comment by cjeon42** [comment]
프론트엔드쪽에서 이미지를 보여줄 때 인증 없이 이미지를 가져오도록 되어있어서 그런 것 같아요

지금은 단순히 `<img src="/api/avatar/default.jpg">` 식으로 가져오게 되어있는데 한번 수정해 보겠습니다
