### ISSUE TITLE
백엔드 웹소켓 class-validation 이슈

### ISSUE THREAD

**Issue by 42-saoh** [exciting-transcendence/transcendence#126]
웹소켓에서 class-validation 이 적용 안 됨
찾아본 결과 웹소켓 gateway에 웹소켓용 pipe 를 적용해야하는 것 같다.
현재 심신미약으로 영어 문서를 잃지 못하므로 이슈를 남긴다.

**Comment by 42-saoh** [comment]
https://github.com/nestjs/nest/issues/3032

**Comment by hoikii** [comment]
1. 게이트웨이에는 global pipe가 적용되지 않는다. (https://docs.nestjs.com/pipes#global-scoped-pipes)
2. 게이트웨이에서 `@usePipe()`하면, 검증실패한 경우 WsExceptionsHandler가 `Bad Request Exception` 던지면서 서버 죽음
  - `Bad Request Exception`은 `HttpException`의 자식인데, WsExceptionsHandler는 `WsException`의 자식만 처리하기 때문
  - custom pipe에서 ExceptionFactory를 이용해 WsException을 던져주면 문제해결
  - https://stackoverflow.com/questions/60749135/
