### ISSUE TITLE
친구추가 및 삭제, 블락 및 언블락, DM, 닉네임 및 아바타 변경 프론트 구현 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#128]
- profile/userAction.tsx 의 유저액션이 구현이 안되어있습니다. 
- 유킴님 구현 중이신지 아님 생각해 놓으신 구조가 있나요?
- 제가 그냥 구현할까요?

**Comment by scarf005** [comment]
쿼리 요청만 보내면 되는거여서 비교적 간단하긴 한데 리액트쿼리 수정 끝나고 하는게 좋을것같아서 미루고있었습니다
생각해보니 api 테스트할겸 간단히 axios.post 한 줄 넣어도 괜찮겠네요

**Comment by peas856** [comment]
리액트쿼리 적용이 시간이 걸린다면 미리 axios로 해놓는게 나을것 같습니다. 
블락 유저의 채팅을 제외하고 백엔드가 메시지를 보내는지 백엔드연결 테스트를 해봐야할 것 같습니다.

**Comment by scarf005** [comment]
그렇다면 axios로 우선 빠르게 구현하고 리액트 쿼리로 전환해야겠네요.

**Comment by scarf005** [comment]
아, 생각해 보니 한꺼번에 바꿀 필요 없으니 이 이슈부터 먼저 리액트 쿼리를 써서 만들면 되겠네요.

**Comment by 42-saoh** [comment]
아바타 변경 : api/avatar/change
아바타 등록과 방식은 같으나 Jwt auth 토큰을 넣어줘야한다.

유저 닉네임 변경 : api/user/nickname
바디에 { "nickname": "string" } 형태로 넣어주면 된다.

**Comment by scarf005** [comment]
위 내용 docs에도 추가 부탁드릴수 있을까요? 스키마 목록에
```
ChangeNicknameDto{
}
```
같이 비어있는 상태에여서요
