### ISSUE TITLE
Public 비밀번호 방 표시 및 클릭 시 비밀번호 모달 창 팝업 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#129]
- 방 리스트 보여주는 부분에서 비밀번호 표시 및 입력 부분 구현 필요
- 방 만들기에서 현재 roomname만 전달해주고 있으나 roomtype 추가해 보내주는 형식으로 수정 예정

@hoikii 
socket.emit('CREATE', roomName:string) 으로 보내주고 있는데 앞으로 어떻게 보내면 되나요?
DTO가 {name:string type: 'Public'|'Private'|'DM' pwd?:string} 인가요?

**Comment by hoikii** [comment]
현재는 
```
{
  roomName: string,
  roomType: "PUBLIC" | " PROTECTED" | "PRIVATE",
  roomPassword?: string
}
```
인데, 용도별로 DTO를 분리하고 정리할 필요가 있을 것 같습니다.
