### ISSUE TITLE
FriendView seenUsers 전체유저->친구목록으로 수정 필요 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#130]
- 현재 친구목록 부분에 전체 유저가 리스팅되고 있습니다. 
- const users = useUserRequest<User[]>('') 되어 있는 부분을 로그인한 유저의 친구목록을 요청한 뒤 친구목록 리스팅으로 바꿔야 할 것 같습니다. 
- 친구 목록이 구현된다면 수정하면 되겠네요

**Comment by scarf005** [comment]
친구목록 api 리퀘스트도 있어야겠네요

**Comment by 42-saoh** [comment]
2 중 1 택 하세요.
1. api 를 요청하면 백엔드에서 토큰으로 해당 유저를 찾고 그 friends 목록으로 user 목록을 찾아 리턴한다.
2. api 에 바디로 해당 유저의 friends[] 를 넘겨줘서 user 목록으로 리턴한다.

**Comment by scarf005** [comment]
1번안이 더 좋을 것 같습니다. `api/user/me/friends` 형식으로 쓰면 될 것 같네요

**Comment by peas856** [comment]
유저 객체 배열로 받고 블락, 친구 목록 빼고,
