### ISSUE TITLE
블락된 사용자의 채팅 메시지 보여주지 않기

### ISSUE THREAD

**Issue by hoikii** [exciting-transcendence/transcendence#136]
뭐가 맞을지 아직도 잘 모르겠지만 일단은 백에서 처리하는걸로 생각하겠습니다.

**Comment by peas856** [comment]
백에서 많이 복잡한가요?
프론트에서 senderUid가 block[] 에 있으면 안보여주도록 구현할 수 있을거 같기도 한데

**Comment by hoikii** [comment]
복잡한 건 아니고 사실 쿼리도 준비되어있긴 해요.

**Comment by peas856** [comment]
네 그럼 백에서 해주세요
프론트 할게 너무 밀려서 ㅠㅠ 인력부족
