### ISSUE TITLE
빈 채팅방 삭제

### ISSUE THREAD

**Issue by hoikii** [exciting-transcendence/transcendence#137]
1. owner(최초 방을 만든 사람)이 나가면 모든 참여자를 내보내고 방 삭제
2. 마지막 남은 참여자가 나가면 방 삭제
## 문제점
두 방법 모두 누군가 명시적으로 방을 나가지 않고 그냥 탭을 닫는다거나 하면 채팅방이 영원히 남아있습니다.
소켓 연결 종료시 방을 나간 걸로 간주한다면, 다시 로그인 또는 새로고침했을 때 기존 채팅방에서 빠져나가버릴 것 같습니다.

**Comment by peas856** [comment]
2 번이 나을것 같습니다. 
다시 접속 시 접속중인 채팅방은 남아있기 때문에 유저가 나가지 않는다면 채팅방이 영원히 남아있는건 문제되지 않는 것 같습니다. 

다만 오너가 나가면 다른 누군가에게 오너를 이전해줘야하는 로직이 추가되어야 하겠네요

**Comment by peas856** [comment]
1번 결정-> 각 참여자는 NOTICE 이벤트로 LEAVE를 받는 것.
