### ISSUE TITLE
채팅 방 나가기 기능 구현 필요, 오너 변경 이슈 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#138]
[프론트]
1. 채팅방 나가는 기능 구현 필요합니다

[백, 프론트]
1. 채팅방 나갈 시 백엔드에 socket.emit('LEAVE', ()) 이벤트를 보내면 방 안에 유저들은 NOTICE 이벤트를 받나요? leave이벤트를 보낸 당사자도 NOTICE 이벤트를 받나요?
2. 오너(방개설자)가 방을 나갈시 새로운 오너를 지정해주는 부분을 어떻게 구현할 수 있을까요?

**Comment by hoikii** [comment]
현재는 당사자 포함 모든 유저들에게 NOTICE를 보냅니다

사실 꼭 오너를 이전할 필요가 있을까 싶어요. 그냥 오너 없는 방으로 남겨둬도 문제 없을 것 같아요.
물론 이 경우 오너가 나갔다 다시 들어오는 경우 자동으로 다시 오너 권한을 갖게 될텐데, 뭐 괜찮지 않을까요?

**Comment by peas856** [comment]
`새 채널을 만든 사용자는 채널을 떠날 때 까지 자동으로 채널 소유자로 설정된다.(1) 채널 소유자는 채널 접근을 위한 비밀번호를 추가/변경/삭제 할 수 있다.(2) 채널 소유자는 채널의 관리자이며, 다른 유저를 관리자가 되도록 선택할 수 있다.(3) 관리자는 일정 시간동안 유저들을 강퇴(ban)하고 차단(mute) 할 수 있다.`

- 오너가 없는 방이 좀 이상하긴 하지만 서브젝트에 오너가 필수라는 명시가 없으니까 일단 오너 나가면 없는거로 하죠  사유: 개발일정 촉박

**Comment by peas856** [comment]
- #137

**Comment by scarf005** [comment]
#137 이 겹치는데 닫을까요?

**Comment by peas856** [comment]
owner(최초 방을 만든 사람)이 나가면 모든 참여자를 내보내고 방 삭제
1번 결정-> 각 참여자는 NOTICE 이벤트로 LEAVE를 받는 것.
