### ISSUE TITLE
메시지 보내면 2번 보내지는 버그 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#158]
백엔드에서는 한 번 받는데
랜더링이 2번 되는 프론트쪽 문제인 것 같습니다.

**Comment by scarf005** [comment]
![_13](https://user-images.githubusercontent.com/54838975/185421939-7a3bc29b-0384-4a57-92f8-ca1ef4ea38eb.png)

방에 나갔다 들어올 때마다 메시지가 들어오는 횟수가 증가하고 있습니다. 소켓이 계속해서 열리는 걸까요?

**Comment by scarf005** [comment]
![_01](https://user-images.githubusercontent.com/54838975/185431541-bfbd1b29-9680-410d-a5a0-79f1ba3872f9.png)
chat 탭을 누를 시 `/api/chat/joinlist` 요청도 두 번 실행되고 있습니다.

**Comment by peas856** [comment]
useeffect가 여러번 실행되면서 소켓 이벤트가 중복으로 등록되는 것이 문제였습니다. 
return () => {
      socket.removeAllListeners('NOTICE')
    }

return () => {
      socket.removeAllListeners('RECEIVE')
    }

이런식으로 useEffect 안에 등록된 소켓 이벤트마다 return으로 등록된 이벤트를 제거해주면 해결이 되지만... 뭔가 임시방편인 느낌이 들어서 PR로는 올리지 않고 내일 방법을 찾아봐야할것 같습니다.

**Comment by peas856** [comment]
위에 언급한 것도 updataRoom이 useEffect [myUid]에 의존하여 이벤트가 등록되는데 myUid가 undefined에서 숫자로 바뀔때 2번 등록되어 updateRoom이 두 번 실행되어 그런 것으로 추정됩니다. 즉 소켓 이벤트리스너를 useEffect 안에 넣어서 생긴 문제인데 지금은 위에처럼 임시방편으로 해결하시고 내일 좋은 해결책을 찾는걸로 ㅎㅎㅎ
