### ISSUE TITLE
아바타 업로드 시 모두가 동일한 아바타로 변함

### ISSUE THREAD

**Issue by scarf005** [exciting-transcendence/transcendence#161]
![_10](https://user-images.githubusercontent.com/54838975/185366056-78a008f5-af5a-4397-b4da-910580144532.png)

**Comment by cjeon42** [comment]
지금 더미 유저가 전부 처음 생성한 유저의 아바타와 동일한 아바타를 사용하도록 되어있어서 그런 것 같아요
