### ISSUE TITLE
채팅방 본인이 보낸 메시지 RECEIVE 안되는 현상 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#165]
현재 본인이 보낸 채팅은 채팅방에 표시 안되고있음

---
원인
- RECEIVE가 안되기 때문
- 소켓 이벤트를 받지 않고 채팅방에 표시 할 수는 있으나 ChatView의 messages에 저장이 안됨(다른방 갔다 들어오면 표시안됨)
---
해결 제안
- 본인 메시지도 RECEIVE로 받게 하는 것이 어떠신지

**Comment by hoikii** [comment]
간단한 쪽으로 해결하죠. sender 자신의 메시지도 RECEIVE로 돌려주도록 수정하겠습니다.
