### ISSUE TITLE
`/chat` 에서 새로고침시 오류

### ISSUE THREAD

**Issue by scarf005** [exciting-transcendence/transcendence#169]
![_12](https://user-images.githubusercontent.com/54838975/185417880-321573a2-cc4d-4a9e-b5d6-b1cd1b6469ce.png)

소켓을 불러오지 못하는 것으로 보임

**Comment by peas856** [comment]
- 현재 MainRouter에서 소켓을 생성하고 해당 컴포넌트 unmount시 소켓이 disconnect되기 때문에 /chat으로 새로고침하면 소켓을 연결하지 못합니다. 
- 해결방법은 생각해보는거로..
