### ISSUE TITLE
`User` 요청 쿼리

### ISSUE THREAD

**Issue by scarf005** [exciting-transcendence/transcendence#17]
# DTO
```ts
type gameID = string
type userID = string

interface Stat {
  wins: number
  loses: number
  draws: number
  rating: number // elo rating
}

interface User {
  id: userID
  name: string
  avatar: string
  status: 'ONLINE' | 'OFFLINE' | gameID
  friends: userID[]
  blocks: userID[]
  stat: Stat
}
```
* 수정: id와 사용자명 모두 반환

# `GET /user`
모든 사용자 목록 불러오기
## 사용하는곳
- 채팅방 목록
- 친구 목록
## 요청
```ts
let response: User[]
```

# `GET /user/{userPID}`
단일 사용자 불러오기
## 사용하는곳
- 친구 / 사용자 프로필
## 요청
```ts
let response: User
```

**Comment by cjeon42** [comment]
GET /user 는 존재하는 모든 유저 목록을 가져오나요?

**Comment by scarf005** [comment]
네 맞아요

**Comment by cjeon42** [comment]
모든 유저를 가져와야 하는 경우가 있나요?

**Comment by peas856** [comment]
유저 수가 많지 않음을 가정하고 친구목록을 불러들이거나 유저 검색을 할때 모든 유저를 가져와 매칭하려했습니다

**Comment by 42-saoh** [comment]
@scarf005
friends: User[]
blocks: User[]
friends 와 blocks 의 User 정보에서 필요한 정보는 뭐일까요?
id: string
name: string
avatar: string
status: 'ONLINE' | 'OFFLINE' | gameID
stat
이렇게 5개 일까요?

**Comment by scarf005** [comment]
> friends 와 blocks 의 User 정보에서 필요한 정보는 뭐일까요?

생각해 보니 어차피 추가로 쿼리를 하는 편이 나을 것 같네요.
friends와 blocks의 dto를 `User[]`에서 `userID[]`로 수정하겠습니다.

**Comment by 42-saoh** [comment]
> 생각해 보니 어차피 추가로 쿼리를 하는 편이 나을 것 같네요. friends와 blocks의 dto를 `User[]`에서 `userID[]`로 수정하겠습니다.

userID[] 이면 그냥 number[] 나 string[] 일까요?

**Comment by scarf005** [comment]
> userID[] 이면 그냥 number[] 나 string[] 일까요?

맞습니다. 위에서 `type userID = string`으로 설정했어요
