### ISSUE TITLE
Profile, Friend 탭 합치기 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#19]

**Comment by scarf005** [comment]
- [x] [List](https://mui.com/material-ui/react-list/) 사용해서 친구 탭 표시하기
  - [x] 리스트 맨 위에 자기 프로필 표시되게 하기
  - [x] 친구 탭 클릭 시 우측 화면에 프로필 표시되게 하기
- [x] 검색 기능 추가
