### ISSUE TITLE
프로젝트 설정

### ISSUE THREAD

**Issue by scarf005** [exciting-transcendence/transcendence#20]
# Eslint
- 프론트, 백엔드 통일?

# 변수, 함수 명명 규칙
- 따를 스타일?

# 커밋, 풀 리퀘스트, 브랜치 명명 규칙
- Conventional Commit?
- 한글 사용?

**Comment by cjeon42** [comment]
eslint는 유킴님이 설정하신 그대로 백엔드 프론트엔드 통일해서 사용하면 될 것 같고

변수, 함수 명명 규칙은
변수, 함수의 경우 `camelCase`
클래스, 타입, 인터페이스 같은 경우 `PascalCase`
그 외 상수, enum 같은 경우 `SNAKE_UPPERCASE` 형식이 어떨까요?

커밋은 vscode 사용하시면 conventional commit 익스텐션 사용하면 좋을 것 같고,
pr제목은 이슈 번호와 함께 어떤 것을 수정했는지를 간략히 설명하는 내용을 담고
브랜치 명명 규칙은 포크해서 작업하면 각자 저장소에서 생길테니까 크게 상관 없을 것 같아요.
커밋, pr, 브랜치 등에서 한글 / 영어 사용은 각자 편하신대로 하셔도 될 것 같습니다.

**Comment by hoikii** [comment]
eslint, 네이밍컨벤션은 cjeon님 제안에 찬성합니다.
커밋컨벤션 관련 vscode확장은 써본적 없긴 한데, 태그든 라벨이든 (인증/프로필/채팅/퐁/기타) 정도는 구분되면 좋을 것 같아요.
아님 이것들을 develop의 섭브랜치로 만들어도 될 것같은데, 그럼 기껏 브랜치 통합한 취지가 무색해질것같기도...

**Comment by scarf005** [comment]
`{대주제}/{소주제}` 형식으로 브랜치명을 만들면 어떨까요? 브랜치 통합한 것은 `front`랑 `back` 모두 서로가 서로를 필요할 수도 있어서 합친 거여서, 단일 `develop` 브랜치에서 퍼져나온 브랜치라면 괜찮을 것 같습니다.

**Comment by peas856** [comment]
네 저도 동의합니다

**Comment by scarf005** [comment]
## 코딩 스타일
> 변수, 함수 명명 규칙은
변수, 함수의 경우 camelCase
클래스, 타입, 인터페이스 같은 경우 PascalCase
그 외 상수, enum 같은 경우 SNAKE_UPPERCASE 형식

## 커밋명
되도록이면 [conventional commit](https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits) 쓰기
예) `feat: OAuth 인증 기능 추가`, `fix: 버튼 연타시 무한 로딩 해결 (#42)`

## 브랜치명
자유롭게, 세부적으로 나눈다면 `{대분류}/{소분류}`

이렇게 정하겠습니다.
