### ISSUE TITLE
`UidDto`의 uid 타입이 `string`임

### ISSUE THREAD

**Issue by scarf005** [exciting-transcendence/transcendence#201]

**Comment by cjeon42** [comment]
`uid.dto.ts` 파일에

```ts
export class UidDto {
  @IsNumberString()
  @IsNotEmpty()
  uid: string
}
```

말씀하시는 건가요?

이 Dto는 url 파라미터로 쓰일 때 사용하는 dto이고
json을 제외한 url 파라미터, 쿼리 파라미터 등은 타입을 표시할 수 없어서 무조건 string으로밖에 안받아지더라고요
대신 IsNumberString() 데코레이터를 넣어서 문자열 전체가 숫자일 때만 유효성 검사를 통과하게 했습니다
