### ISSUE TITLE
DM방에서 처음 DM을 보낸 사람이 나가면 나가면 방 폭파됨

### ISSUE THREAD

**Issue by hoikii** [exciting-transcendence/transcendence#226]
- 그냥 이대로 둘지
- DM방의 경우 모든 참여자가 나가야 방이 없어지게 할지
- 현재 DM방에서 제3자 초대 가능

**Comment by peas856** [comment]
1. DM방은 초대할 수 있는 컴포넌트가 유저에게 안보입니다. 따라서 초대 불가능
2. DM방의 경우 모든 참여자가 나가야 방이 없어지게 할지 -> 이 경우 문제가 a가 b에게 DM을 걸어 대화하다 a가 나가고 다시 b에게 DM을 하면 방이 또 생기는 문제가 있을 것 같습니다. (b는 a와 DM방 2개)
3. 따라서 그냥 이대로 두는게 어떨지..

**Comment by hoikii** [comment]
2번의 경우 사실 현재 구현에서도 같은 문제가 예상되므로 #225 에서 따로 해결해야 할 것 같습니다.
