### ISSUE TITLE
Friend Tab에서 유저 검색시 뜨는 프로필에서 DM버튼 안보이게 수정 필요 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#228]
현재 Friend Tab에서도 DM이 보이나 기능 구현이 안되어있으므로 삭제 필요

**Comment by scarf005** [comment]
기능 구현이 되면 다시 추가해야한다는 뜻인가요? friend tab에서는 DM버튼이 있으면 안 된다는 뜻인가요?

**Comment by peas856** [comment]
friend tab에있는 DM버튼 누르면 정상작동 하나요? 이슈올릴때는 작동을 안햇었는데 만나서 확인해보시죠!

**Comment by scarf005** [comment]
이전 버전 API에서 방만 만들어집니다. 새 API로 바꾸면 될 것 같습니다
