### ISSUE TITLE
채팅방에서 유저 클릭시 나오는 모달창 - 프로필 연동 문제 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#230]
- 채팅창에서 유저 클릭시 나오는 모달창에서 프로필 컴포넌트를 그대로 사용 중
- 유저프로필 변경 버튼 등 불필요한 기능도 그대로 노출됨
- Friend Tab에서의 프로필과 채팅방에서의 프로필 구분 필요

**Comment by scarf005** [comment]
채팅에서는 기존 프로필 컴포넌트에 채팅 기능을 추가하려고 생각했는데, 그렇다면 둘을 아예 별개로 구분할까요?

**Comment by peas856** [comment]
'채팅에서는 기존 프로필 컴포넌트에 채팅 기능을 추가하려고 생각했는데' -> 이 부분이 정확히 이해가 안갑니다

채팅인터페이스에서 다른 유저의 프로필에 접근할 수 있어야 해서 프로필 컴포넌트 재활용은 문제가 없는데.. 저희가 프로필컴포넌트에 마이페이지 기능이 들어가있어서 문제인것 같아요. 사실 닉네임 수정이나 아바타 변경은 마이페이지에서 할 일인데 그게 FriendTab의 내 프로필보기에 들어가 있어서..

**Comment by scarf005** [comment]
아, 채팅방에서 필요한 버튼을 말하는 거였어요
접속한 사용자 프로필은 새로 만드는 것이 맞겠지만, 다른 사용자에 경우 채팅방 내부에서도 친구 추가나 밴을 할 수 있어야 할 것 같아서 버튼을 추가하려고 했었어요

**Comment by peas856** [comment]
다른 사용자의 경우 그대로 써도 되겠네요. 접속한 사용자 프로필은 새로 하는게 나을것같아요

**Comment by scarf005** [comment]
27ef8ffaead93f3aef3138764fa0cdf85eb80e6f 에서 해결
