### ISSUE TITLE
프론트엔드 UI 및 디자인 변경 

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#255]
- 폰트변경
- 색상 정하기
- 구조 변경
- 배경이미지 등 이미지 활용
- 레퍼런스 사이트를 댓글로 달아주세요 

제안 
--- 
[이미지1]
![Game tab - Page 1](https://user-images.githubusercontent.com/42163769/186152814-a8c19149-c947-4aee-9fe9-55188e14c26c.png)
1. 크게 왼쪽탭, 메인탭, 오른쪽 탭으로 나눔
2. 오른쪽 탭은 친구목록으로 고정(아래 이미지)
<img width="287" alt="스크린샷 2022-08-23 오후 9 02 30" src="https://user-images.githubusercontent.com/42163769/186153056-4bbc1ed9-2aee-4be8-a2c3-59d555f509d9.png">
3. 왼쪽탭은 이미지1의 게임버튼, 챗 버튼 클릭에 따라 게임버튼 클릭시 이미지1의 왼쪽 박스로 변경, 챗 버튼 클릭 시 아래이미지
<img width="332" alt="스크린샷 2022-08-23 오후 9 03 22" src="https://user-images.githubusercontent.com/42163769/186153213-8145fb91-4bb4-4ce0-a276-b489437e952a.png">
4. 메인탭의 경우 아래와 같은 컴포넌트들이 보여진다. 
<img width="753" alt="스크린샷 2022-08-23 오후 9 04 06" src="https://user-images.githubusercontent.com/42163769/186153350-27295a1d-2443-43ee-a0e1-9991d116114a.png">
<img width="950" alt="스크린샷 2022-08-23 오후 9 04 20" src="https://user-images.githubusercontent.com/42163769/186153398-1069f126-5b89-48c7-89fc-fae3ecfc02d8.png">
<img width="974" alt="스크린샷 2022-08-23 오후 9 04 34" src="https://user-images.githubusercontent.com/42163769/186153446-f8285c69-66bd-49ee-9794-e958523ba26f.png">
<img width="795" alt="스크린샷 2022-08-23 오후 9 05 00" src="https://user-images.githubusercontent.com/42163769/186153533-e1d83289-12b7-4742-b038-34a309377fc7.png">
<img width="667" alt="스크린샷 2022-08-23 오후 9 05 12" src="https://user-images.githubusercontent.com/42163769/186153573-79ab50ed-0bec-479a-8216-ec109925048a.png">

**Comment by peas856** [comment]
- 배경으로 쓸 백그라운드 이미지+이펙트 제안 
- https://codepen.io/thdoan/pen/YmNVgx
- https://codepen.io/sharnajh/details/WNvppRy

**Comment by peas856** [comment]
색상은 https://www.webdesignrankings.com/resources/lolcolors/
에서 확인할 수 있다시피 보통 공인된 색상조합을 2-4가지 사용합니다만

저는 앱등이로서 블랙앤화이트 심플이스베러를 추천합니다

**Comment by scarf005** [comment]
좋은 것 같습니다. 컴포넌트는 재배치만 하나요, 아니면 내부 코드도 같이 리팩터링하나요? (roomId 등을 전역 변수로 옮기기)

**Comment by peas856** [comment]
컴포넌트 재배치하면 prop 전달현상이 심해질 것이므로.. 극혐인 변수와 상태만 전역으로 옮기는게 낫지 않을까요 시간상..

**Comment by scarf005** [comment]
그러면
1. 변수/상태 골라서 전역으로 이동
2. 컴포넌트 위치 조정
3. 배경화면/테마 적용

이 순서대로 진행될까요?

**Comment by peas856** [comment]
2->1 이 낫지 않나요? 전 상관 없습니다. 감이 잘 안오네요. 
+색상 및 폰트 변경

**Comment by 42-saoh** [comment]
더 필요한 api 가 있을까요?

**Comment by scarf005** [comment]
우선은 1번과 2번은 새 이슈로 만들어보겠습니다

**Comment by scarf005** [comment]
- #274 
- #275

**Comment by peas856** [comment]
구글폰트
https://fonts.google.com/
사용법
https://developers.google.com/fonts/docs/css2
