### ISSUE TITLE
인자들을 전역 변수로 빼내기

### ISSUE THREAD

**Issue by scarf005** [exciting-transcendence/transcendence#275]
- react-dom을 적극적으로 이용하는 것도 좋을 것 같습니다. 가령 
  - `localhost:3000/chat/{채팅방 id}`
  - `localhost:3000/game/{game id}`

- 컨텍스트 관리자를 선택해야 합니다. 
  - react context, recoil, redux등이 있습니다.
  - 위 라이브러리 중 하나를 선택해 `uid` 등을 빼내야 합니다.

**Comment by peas856** [comment]
1. 저렇게 하면 다른 유저가 권한이 없는 채팅방이나 게임으로 접근할 수 없는 문제는 없나요?(url을 통해) 최대한 백엔드와의 충돌을 피하는 쪽으로 리팩토링 해야할 것 같습니다. 
2. 저는 context는 익숙하고 나머지 둘은 잘 모릅니다. 유킴님이 recoil 익숙하면 써도 되는데 너무 적극적인 사용은 학습시간이..^^

**Comment by scarf005** [comment]
아 혹시 이중에 편하신게 있나 해서 올려봤습니다. 컨텍스트 자주 쓰셨으니 컨텍스트 쓰시죠

**Comment by peas856** [comment]
https://velog.io/@gygy/useReducer-useContext-%EB%A6%AC%EB%8D%95%EC%8A%A4%EB%A5%BC-%EB%8C%80%EC%B2%B4%ED%95%A0-%EC%88%98-%EC%9E%88%EB%8A%94-react-hooks

useReducer 도 같이 쓸 수 있겠네요
