### ISSUE TITLE
prod 모드 레지스터으로 callback 이 안 됨

### ISSUE THREAD

**Issue by 42-saoh** [exciting-transcendence/transcendence#278]
<img width="560" alt="스크린샷 2022-08-24 오후 2 46 12" src="https://user-images.githubusercontent.com/72004176/186340126-760b541f-e742-4c9e-a58e-90be238f6d9f.png">

intra 로그인 후 callback 되는 부분에서 에러 발생

**Comment by 42-saoh** [comment]
callback 후의 문제인듯 싶기도 함

**Comment by scarf005** [comment]
혹시 #277 이전 prod에서는 잘 동작했나요?

**Comment by 42-saoh** [comment]
그건 확인해보진 못했습니다만 아마 #277 pr 이 문제이진 않을 것 같습니다
