### ISSUE TITLE
중복 로그인시 가능한 문제

### ISSUE THREAD

**Issue by hoikii** [exciting-transcendence/transcendence#284]
1. 나 자신과의 게임
2. a1이 '방만들기'한 결과가 a2의 '참여중인 채팅리스트'에 반영되지 않음
3. b가 만든 방에 a1이 참여한 결과가 a2의 '참여중인 채팅리스트'에 반영되지 않음

2,3번 모두 백에서 간단히 처리가 가능할 것 같은데, 대신 a에게는 NOTICE가 두 번 갑니다.
누가 들어오고 나갔는지 채팅창에 보여주지는 않기 때문에 큰 문제는 없을 것 같습니다.

1번도 간단히 처리할 수 있지 않을까 싶은데 @42-cjeon 어떠신가요? 아님 아예 중복로그인 자체를 막는게 나을까요?

**Comment by cjeon42** [comment]
소켓에서는 중복 연결 안되게 막아야 할 것 같아요

**Comment by hoikii** [comment]
채팅의 경우 각 탭에게 전부 메시지를 뿌려주고 있긴 한데, 전부 막고 첫 탭에게만 보낼까요?
아님 퐁 소켓만 중복을 막을까요?
