### ISSUE TITLE
첫번째 dm 메시지를 수신하지 못함

### ISSUE THREAD

**Issue by hoikii** [exciting-transcendence/transcendence#287]
a가 b에게 첫 dm을 보냈을 때, a의 메시지를 b가 확인할 수 없음
  - DB에도 소켓도 a,b 모두 채팅방에 참여된 것으로 확인
  - b가 채팅탭을 보고 있을 때는 정상 동작함

**Comment by scarf005** [comment]
`ChatView` 컴포넌트에서 렌더링을 처리하기 때문에 컴포넌트가 렌더링되지 않을 때에는 메시지를 받지 못하는 것 같습니다. 해결법은 생각해 봐야겠네요...

**Comment by peas856** [comment]
현재 ChatView에서 useEffect로 NOTICE, RECEIVE, DESTROY 등의 이벤트 핸들러를 등록시킨 후 컴포넌트가 언마운트될때 이벤트 핸들러 등록을 모두 취소시키고 있습니다(중복등록방지) 따라서 다른 탭에 있을 때는 이벤트에 대한 동작을 제대로 수행하지 못하고 있는 것 같은데 이벤트 등록을 모두 Main 쪽에서 처리해야 다른 탭에서도 정상동작 할 것 같습니다

**Comment by peas856** [comment]
ChatPanel의 CHATUSER_STATUS 이벤트 역시 이벤트핸들러 등록을 Main으로 옮기기, 기타 Socket.on 부분 모두 체크필요

**Comment by hoikii** [comment]
`my profile`의 user satus도 업데이트가 안되는데 이것도 왠지 같이 해결될 것 같습니다..

**Comment by peas856** [comment]
아 저건 해결될지 모르겠는데..

**Comment by peas856** [comment]
저게 온/오프/게임 이죠? 백에서는 온/오프/게임을 어떻게 판단하나요? 저게 프론트에서 즉각 업데이트가 되려면 온/오프/게임 상태가 변할때마다 소켓으로 이벤트를 받아서 핸들러로 해당 화면을 업데이트 해야합니다.(예를 들면 본인 프로필, 친구목록 등)

**Comment by hoikii** [comment]
#289
