### ISSUE TITLE
유저 프로필 정보 변동(STATUS, STAT)에 따른 화면 실시간 연동

### ISSUE THREAD

**Issue by peas856** [exciting-transcendence/transcendence#289]
- 유저 프로필(본인, 친구 등 다른유저) 정보는 User 객체 기반으로 생성
- 해당 정보(대표적으로 STATUS, STAT)등이 변할 때 실시간으로 정보 업데이트가 안됨
- 실시간 연동시킬 정보(정해야함)가 변동될 때 소켓으로 이벤트를 받아 쿼리 invalidate를 하면
- 채팅에서 프로필 접근시, 친구목록(오른쪽 탭)에서 프로필 접근 시 실시간으로 정보 변동될  것으로 예상됨
- 소켓이벤트 핸들러 등록 위치 주의

**Comment by hoikii** [comment]
DB에는 채팅소켓 연결/종료시, 게임 시작/종료시마다 업데이트하고 있습니다.
실시간으로 바뀐걸 보여주려면 역시 이벤트를 새로 보내긴 해야 할 것 같습니다.
근데 실시간까진 아니어도 새로고침하거나 다른 탭으로 이동할 때만이라도 바뀌었음 좋겠는데, `my profile`부분은 어째선지 바뀌지가 않네요.

**Comment by peas856** [comment]
확인해보겠습니다. 지금 다른 작업중이라 ㅠ
실시간 변경이 아니라면 해결은 쉽습니다. 아마 my profile은 변동이 없기때문에(이벤트가 없어) 데이터를 다시 요청하는 코드가 없어 그런것 같네요

**Comment by scarf005** [comment]
`my profile`에서 어떤 부분을 변동하게 할까요?

**Comment by hoikii** [comment]
![tmp](https://user-images.githubusercontent.com/95955033/186800887-5f38aab7-615a-42b2-8030-8dd5a946bc4f.png)

**Comment by peas856** [comment]
오른쪽 탭 클릭시 invalidate
