### ISSUE TITLE
Private 에서 owner가 본인을 초대하면 초대가 가능함

### ISSUE THREAD

**Issue by 42-saoh** [exciting-transcendence/transcendence#294]
예전에 owner 를 방에 2번 넣었던 로직때문에 발생한 것 같다.

chat.gateway : 504
for (const soc of sockets) {
      try {
        await this.chatService.addUserToRoom(invitee, roomId, null, isInvite)
      } catch (error) {
        return error
      }
      soc.join(roomId.toString())
    }

chat.service : 119
addUserToRoom {
...
room.chatUser.map((chatUser) => {
      if (chatUser.user.uid === user.uid && !chatUser.isOwner) { <<  !chatUser.isOwner 여기서 발생하는 문제
        throw new BadRequestException('User already in room')
      }
    })
...
}

**Comment by hoikii** [comment]
#297 에서 초대받는 사람이 이미 방에 들어있는지 확인하는걸 추가했는데, 왠지 같이 해결될 것 같네요.
