### ISSUE TITLE
접속하지 않은 유저를 초대하면 서버창에 join은 뜨는데 유저는 add 되지 않음

### ISSUE THREAD

**Issue by 42-saoh** [exciting-transcendence/transcendence#295]
PRIVATE 채팅방에서 초대하면
CLI 에선 join 이벤트가 발생했다 나오지만 유저는 add되지 않고 db에 추가되지 않는다

<img width="1135" alt="스크린샷 2022-08-25 오전 8 50 05" src="https://user-images.githubusercontent.com/72004176/186543654-b6e8026f-10dc-4edd-ae9a-3b90737bb954.png">
.

**Comment by hoikii** [comment]
초대받은 사람이 다시 로그인하면 동작이 이랬다 저랬다 하는데,
오프라인인 사람을 초대 못하게 하는 게 낫겠네요
