### ISSUE TITLE
아바타 이미지

### ISSUE THREAD

**Issue by 42-saoh** [exciting-transcendence/transcendence#3]
- nginx 리버스 프록시 에서 정적 파일로 제공
- 프로필쪽에서 uuid 경로로 접근할 수 있도록

**Comment by peas856** [comment]
- 아바타 이미지를 후보군 몇 개 중 선택하는 것으로 할지, jpg 이미지로 할지, 이미지 링크주소로 할지 결정 필요 
- 1안이 편할듯
- 2안 및 3안은 이미지 사이즈를 잘라야 할것 같고 3안은 로딩시간이 좀 걸릴듯

**Comment by scarf005** [comment]
링크 주소로 하는 게 구현하기 간단할 것 같기는 하네요

**Comment by peas856** [comment]
- 이미지 파일로 받아서 formdata 형태로 닉네임, 2차인증여부, 이미지 모두 넘겨줄 예정
