### ISSUE TITLE
Mute된 사용자가 채팅방을 나갔다 들어왔을 때 바로 메시지를 보낼 수 있음

### ISSUE THREAD

**Issue by hoikii** [exciting-transcendence/transcendence#303]
## 원인
채팅방을 나가면 isMuted를 갖고 있는 chatUser가 삭제됨

## 해결
 - 삐빅 정상입니다
 - 한 번 추가된 chatUser는 삭제하지 말고, chatUser에 isJoined 항목 추가, `findRoomsByUserId()`와 `getJoinChatrooms()` 등에서 isJoined인 chatUser만 리턴

**Comment by 42-saoh** [comment]
삐빅 정상입니다. 악용시 admin이 밴으로 철퇴를
