### ISSUE TITLE
채팅, 매치 수정사항

### ISSUE THREAD

**Issue by scarf005** [exciting-transcendence/transcendence#320]
- [x] 채팅창 스크롤
- [x] 채팅창 크기 고정
- [x] 매치 기록 스크롤
- [x] 매치 기록 글자 크기 줄이기?
- [ ] 채팅 목록 보이기  (`/chat` 부분 수정)
- [x] 친구 초대에서 엔터 누를시 이상한 곳으로 이동됨

**Comment by 42-saoh** [comment]
채팅 초대창에서 enter 키 누르면 새로고침 된다.  -> 해결

**Comment by peas856** [comment]
- 매치 후 본인 STAT invalidate 해주기(오른쪽 프로필창에 변화가 없음) -> 수정

**Comment by peas856** [comment]
- [] 채팅방 참여중인 유저도 스크롤
