### ISSUE TITLE
유저 차단기능 추가

### ISSUE THREAD

**Issue by 42-saoh** [exciting-transcendence/transcendence#6]
# 프론트엔드
- [x] 프로필에 차단 버튼 추가

# 백엔드
- [x] `blockUser` 또는 `user` 수정 기능?

**Comment by scarf005** [comment]
아직 버튼과 백엔드 요청 부분이 연결되지 않아 다시 엽니다.

**Comment by scarf005** [comment]
#128 번에서 진행
