### ISSUE TITLE
ID 등록할때 avatar 입력없이 등록할 경우 error 발생

### ISSUE THREAD

**Issue by 42-saoh** [exciting-transcendence/transcendence#65]
error 발생이유 : user entity 의 avatar 가 null 값을 받음

에러 해결 방법 : 
1. 백엔드 entity 에서 avatar 의 속성 필드 nullable 을 설정
2. 백엔드 entity 에서 avatar 의 디폴트 값을 설정(디폴트 이미지를 생성하거나, 볼륨을 연결해서 디폴트 이미지를 갖게함)
3. 프론트에서 이미지를 업로드 안 했을경우(image name이 없을경우), name 중복체크하세요 와 같은 창을 띄워준다.

어떤것이 좋을지 의견 부탁드려요~

**Comment by peas856** [comment]
2번이 좋을거같아요
- 사용자는 아바타를 업로드할 수 있어야함. 사용자가 아바타를 업로드 하지 않으면 기본 아바타 설정.

**Comment by peas856** [comment]
프런트에서도 이미지를 고르기 전에 디폴트 이미지를 미리보기로 보여줘서 같은 파일 이미지 파일로 백 프런트 다 가지고 있으면 될거같아요

**Comment by 42-saoh** [comment]
그러면 되겠네요. 확인했습니다.
