### ISSUE TITLE
닉네임 중복확인 불가

### ISSUE THREAD

**Issue by hoikii** [exciting-transcendence/transcendence#85]
a05b8163f59bcd65cd7eb8bb3e043a50762e90b4 부터 닉네임 중복확인시 `User not found`를 리턴합니다.
금방 해결 안된다면 revert 후 다시 작업하는 것도 괜찮을 것 같습니다.

**Comment by 42-saoh** [comment]
오우~ 에러 쓰로우 만드는 과정에서 에러가 발생했네요~ 아주 즐거운 현상입니다

**Comment by 42-saoh** [comment]
현재 닉네임 중복확인은 어떤 api 로 진행하시고 계신건가요?

**Comment by 42-saoh** [comment]
backend/app/src/user/user.service.ts 파일에서 102번줄 부터 106번 return user 전까지 싹 날려주시면 됩니다.

**Comment by scarf005** [comment]
- #76 과 별개의 이슈인가요?

**Comment by 42-saoh** [comment]
- #76  과 별개 이슈지만 이번 trhee 님의 pr 에 추가해서 같이 pr 하겠습니다.
