### ISSUE TITLE
Recoil 제거

### ISSUE THREAD

**Issue by cjeon42** [exciting-transcendence/transcendence#92]
Recoil은 기본적으로 순수 함수를 가정하고 만들었기 때문에 Recoil 자체의 set을 거치지 않고 값이 변할 수 있는 상황에서 유용하게 사용할 수 없음

**Comment by scarf005** [comment]
앗... 지금 다 리코일로 바꾸고 있었는데...

**Comment by cjeon42** [comment]
예를 들어서

```ts
const withMe = selector({
   key: 'WithMe',
   get: async ({ get }) => {
      const res = await fetch('/api/user/me')
      
      const data = await res.json()
      
      return data
   }
})
```

같은 셀렉터에서 값을 사용할 때 

```ts
const me = useRecoilValue(withMe)
```
같이 쓸 수 있는데,

서버측에서 me가 바뀌었을 때 withMe 셀렉터는 의존성이 없어서 페이지 전체를 새로고침 하기 전까지 바뀌지 않습니다...

이걸 해결하려면 unstable이 붙어있는 refresher을 사용하거나 (사용하더라도 서버 측에서 값이 바뀌는 순간을 알아야 함)
서버 측의 값을 꾸는 모든 요청을 recoil을 통해서 보내줘야 하는데 차라리 커스텀 훅을 만드는게 더 편할 것 같더라고요

저는 주로 fetch를 사용하는 시나리오에서 recoil을 사용하려고 했는데 앞서 말한 문제점들 때문에 생각을 더 해봐야 할 것 같고
혹시 다른 부분에서 저러한 문제점 없이 사용할 수 있다면 계속 사용하시는 것도 좋을 것 같아요

**Comment by scarf005** [comment]
지금처럼 http api를 사용하는 방식이라면 계속해서 정보를 동기화하기 힘들 것 같은데, 그렇다면
- 웹소켓 사용
- 동기화가 되는 라이브러리 도입 
중에 하나를 해야 되겠네요

**Comment by scarf005** [comment]
카카오페이에서 [리액트 쿼리 라이브러리에 대한 소개문](https://tech.kakaopay.com/post/react-query-1/)을 올렸는데, 저희 상황에 맞는 것 같네요
기존 recoil로 사용하던 부분을 react-query로 바꾸면 좋을 것 같습니다
